language: c

env:
  - LUA=lua5.1
#  - LUA=lua5.2

install:
  - sudo apt-get  install -qq lua5.1
  - sudo apt-get  install -qq lua5.2
  - sudo apt-get  install -qq luajit
  - sudo apt-get  install luarocks
  - sudo luarocks install lua-testmore
  - sudo luarocks install lua-testlongstring
  - sudo luarocks install lzlib ZLIB_LIBDIR=/lib/x86_64-linux-gnu/
  - sudo luarocks install zipwriter
  - sudo ln -s /usr/local/share/lua/5.1 /usr/local/share/lua/5.2

script:
  - prove --exec="$LUA" --ext=lua -r test/unit
